version: '3.7'
services:
    app:
      build: './app'
      container_name: 'app'
      restart: 'always'
      expose:
        - 8000
      env_file:
        - .env
      volumes:
        - type: 'bind'
          source: './volumes/app'
          target: '/app'
      depends_on:
        - "postgres"
        - "nginx"

    postgres:
      image: 'postgres'
      container_name: 'postgres'
      restart: 'always'
      expose:
        - 5432
      env_file:
        - .env
      volumes:
        - type: 'bind'
          source: './volumes/dbdata'
          target: '/var/lib/postgresql/data'


    nginx:
      build: './nginx'
      container_name: 'nginx'
      restart: 'always'
      ports:
        - '80:80'
      volumes:
        - type: 'bind'
          source: './volumes/media'
          target: '/app/media'
        - type: 'bind'
          source: './volumes/static'
          target: '/app/static'